"""Streamlit MVP UI for the single-hop RAG agent (Phase 3).

Run with:
    uv run streamlit run src/sec_10k_agent/api/streamlit_app.py

Shows the answer plus a retrieval trace — the exact chunks that were retrieved,
their similarity scores, and which ones the answer cited — so the retrieval step
is inspectable rather than a black box. The heavy objects (embedding model, DB
engine, LLM client) are built once and cached across reruns.
"""

from __future__ import annotations

import streamlit as st

from sec_10k_agent.rag import RAGPipeline
from sec_10k_agent.rag.models import Answer
from sec_10k_agent.scope import FISCAL_YEARS, TICKERS


@st.cache_resource
def _get_pipeline() -> RAGPipeline:
    """Build the pipeline once per session (loads the embedding model + engine)."""
    return RAGPipeline()


def _run(
    question: str, ticker: str | None, year: int | None, section: str | None, k: int
) -> Answer:
    return _get_pipeline().answer(question, ticker=ticker, fiscal_year=year, section=section, k=k)


def main() -> None:
    st.set_page_config(page_title="SEC 10-K Agent", page_icon="📊", layout="wide")
    st.title("📊 SEC 10-K Agent")
    st.caption(
        "Ask questions about AAPL, NVDA, and JPM 10-K filings (FY2021-2025). Every claim is cited."
    )

    with st.sidebar:
        st.header("Filters")
        ticker = st.selectbox("Ticker", ["(any)", *TICKERS])
        year = st.selectbox("Fiscal year", ["(any)", *FISCAL_YEARS])
        section = st.text_input("Section (e.g. 'Item 1A')", "")
        k = st.slider("Chunks to retrieve", min_value=1, max_value=15, value=5)

    question = st.text_input(
        "Question",
        placeholder="What supply chain risks does Apple disclose?",
    )
    ask_clicked = st.button("Ask", type="primary")

    if not (ask_clicked and question.strip()):
        return

    sel_ticker: str | None = None if ticker == "(any)" else str(ticker)
    sel_year: int | None = None if year == "(any)" else int(str(year))
    sel_section: str | None = section.strip() or None

    with st.spinner("Retrieving and generating…"):
        try:
            answer = _run(question.strip(), sel_ticker, sel_year, sel_section, k)
        except Exception as exc:  # surface config/DB/LLM errors in the UI
            st.error(f"Failed: {exc}")
            st.info(
                "Check that Postgres is running (docker compose up) and a generator is "
                "configured (XAI_API_KEY or OLLAMA_BASE_URL in .env)."
            )
            return

    st.subheader("Answer")
    st.markdown(answer.text)

    cited = set(answer.cited_indices)
    st.subheader(f"Retrieval trace — {len(answer.sources)} chunks")
    if not answer.sources:
        st.warning("No chunks retrieved for these filters.")
    for i, src in enumerate(answer.sources, start=1):
        badge = "✅ cited" if i in cited else "· not cited"
        label = f"[{i}] {src.citation()} — score {src.score:.3f}  ({badge})"
        with st.expander(label, expanded=(i in cited)):
            st.write(src.text)

    if answer.model:
        total = (answer.prompt_tokens or 0) + (answer.completion_tokens or 0)
        st.caption(f"Generated by {answer.model} · {total} tokens")


if __name__ == "__main__":
    main()
